# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui',
# licensing of 'MainWindow.ui' applies.
#
# Created: Wed Oct 23 11:07:45 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(868, 606)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/logo64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(230, 377, 571, 101))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(36)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 201, 271))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 173, 225))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_select_capture_region_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.pushButton_select_capture_region_2.setFont(font)
        self.pushButton_select_capture_region_2.setStyleSheet("")
        self.pushButton_select_capture_region_2.setObjectName("pushButton_select_capture_region_2")
        self.verticalLayout.addWidget(self.pushButton_select_capture_region_2)
        self.pushButton_select_capture_region_3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.pushButton_select_capture_region_3.setFont(font)
        self.pushButton_select_capture_region_3.setStyleSheet("")
        self.pushButton_select_capture_region_3.setObjectName("pushButton_select_capture_region_3")
        self.verticalLayout.addWidget(self.pushButton_select_capture_region_3)
        self.pushButton_select_capture_region_4 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.pushButton_select_capture_region_4.setFont(font)
        self.pushButton_select_capture_region_4.setStyleSheet("")
        self.pushButton_select_capture_region_4.setObjectName("pushButton_select_capture_region_4")
        self.verticalLayout.addWidget(self.pushButton_select_capture_region_4)
        self.pushButton_select_capture_region = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.pushButton_select_capture_region.setFont(font)
        self.pushButton_select_capture_region.setStyleSheet("")
        self.pushButton_select_capture_region.setObjectName("pushButton_select_capture_region")
        self.verticalLayout.addWidget(self.pushButton_select_capture_region)
        self.pushButton_show_capture = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_show_capture.setMinimumSize(QtCore.QSize(99, 28))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.pushButton_show_capture.setFont(font)
        self.pushButton_show_capture.setStyleSheet("")
        self.pushButton_show_capture.setObjectName("pushButton_show_capture")
        self.verticalLayout.addWidget(self.pushButton_show_capture)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(314, 41, 413, 319))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit_product = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lineEdit_product.setFont(font)
        self.lineEdit_product.setText("")
        self.lineEdit_product.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_product.setReadOnly(True)
        self.lineEdit_product.setObjectName("lineEdit_product")
        self.verticalLayout_2.addWidget(self.lineEdit_product)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(411, 191))
        self.lineEdit.setMaximumSize(QtCore.QSize(411, 191))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(90)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 360, 173, 120))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.lineEdit_IP_PLC = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_IP_PLC.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_IP_PLC.setObjectName("lineEdit_IP_PLC")
        self.verticalLayout_3.addWidget(self.lineEdit_IP_PLC)
        self.pushButton_change_ip = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setWeight(50)
        font.setBold(False)
        self.pushButton_change_ip.setFont(font)
        self.pushButton_change_ip.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1.2, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(200, 194, 15);")
        self.pushButton_change_ip.setObjectName("pushButton_change_ip")
        self.verticalLayout_3.addWidget(self.pushButton_change_ip)
        self.pushButton_plc_connect_test = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_plc_connect_test.setMinimumSize(QtCore.QSize(99, 28))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setWeight(50)
        font.setBold(False)
        self.pushButton_plc_connect_test.setFont(font)
        self.pushButton_plc_connect_test.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1.2, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(200, 194, 15);")
        self.pushButton_plc_connect_test.setObjectName("pushButton_plc_connect_test")
        self.verticalLayout_3.addWidget(self.pushButton_plc_connect_test)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 868, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton_change_ip, QtCore.SIGNAL("clicked()"), MainWindow.change_ip_plc)
        QtCore.QObject.connect(self.pushButton_plc_connect_test, QtCore.SIGNAL("clicked()"), MainWindow.test_connect_plc)
        QtCore.QObject.connect(self.pushButton_select_capture_region, QtCore.SIGNAL("clicked()"), MainWindow.select_capture_region)
        QtCore.QObject.connect(self.pushButton_show_capture, QtCore.SIGNAL("clicked()"), MainWindow.show_capture)
        QtCore.QObject.connect(self.pushButton_select_capture_region_2, QtCore.SIGNAL("clicked()"), MainWindow.start)
        QtCore.QObject.connect(self.pushButton_select_capture_region_3, QtCore.SIGNAL("clicked()"), MainWindow.pause)
        QtCore.QObject.connect(self.pushButton_select_capture_region_4, QtCore.SIGNAL("clicked()"), MainWindow.manual_key_read)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "条码打印", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "操作区", None, -1))
        self.pushButton_select_capture_region_2.setText(QtWidgets.QApplication.translate("MainWindow", "开始", None, -1))
        self.pushButton_select_capture_region_3.setText(QtWidgets.QApplication.translate("MainWindow", "暂停", None, -1))
        self.pushButton_select_capture_region_4.setText(QtWidgets.QApplication.translate("MainWindow", "手动读号", None, -1))
        self.pushButton_select_capture_region.setText(QtWidgets.QApplication.translate("MainWindow", "选择识别区域", None, -1))
        self.pushButton_show_capture.setText(QtWidgets.QApplication.translate("MainWindow", "查看识别区域", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "项目:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "钥匙号:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "PLC的IP:", None, -1))
        self.lineEdit_IP_PLC.setText(QtWidgets.QApplication.translate("MainWindow", "192.168.0.255", None, -1))
        self.pushButton_change_ip.setText(QtWidgets.QApplication.translate("MainWindow", "设置为当前值", None, -1))
        self.pushButton_plc_connect_test.setText(QtWidgets.QApplication.translate("MainWindow", "测试连接", None, -1))

import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

